# Generated by Django 4.1.5 on 2023-01-09 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskcategory",
            options={
                "ordering": ["-title"],
                "verbose_name": "Категория задачи",
                "verbose_name_plural": "Категории задач",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Комментарий")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Архивирован"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.comment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="journal.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "users_acquainted",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comments_acquainted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ознакомлены",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["task", "-created"],
            },
        ),
    ]
