version: "3.9"
services:
  redis:
    container_name: "journal-redis"
    image: redis:7.0.4
    volumes:
      - ./data/redis:/data
  web:
    container_name: "journal-web"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - "SECRET_KEY="
      - "DEBUG=True"
      - "HOST_NAME=http://127.0.0.1"
      - "STATIC_ROOT=staticfiles"
      - "ROLLBAR_ACCESS_TOKEN="
    depends_on:
      - redis
  worker:
    container_name: "journal-worker"
    build: .
    volumes:
      - .:/code
    command: ['celery', '--workdir=/code', '-A', 'django_project', 'worker']
    environment:
      - "SECRET_KEY="
      - "DEBUG=True"
      - "HOST_NAME=http://127.0.0.1"
      - "ROLLBAR_ACCESS_TOKEN="
      - "TELEGRAM_BOT_TOKEN="
      - "TELEGRAM_ADMIN_ID=133637887"
  # Nginx config inspired by: https://saasitive.com/tutorial/django-celery-redis-postgres-docker-compose/
  nginx:
    container_name: "journal-nginx"
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      - web