version: "3.9"
services:
  web:
    container_name: "journal-web"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - "SECRET_KEY="
      - "DEBUG=True"
      - "STATIC_ROOT=staticfiles"
      - "ROLLBAR_ACCESS_TOKEN="
  # Nginx config inspired by: https://saasitive.com/tutorial/django-celery-redis-postgres-docker-compose/
  nginx:
    container_name: "journal-nginx"
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      - web