version: "3.9"
services:
  redis:
    container_name: "journal-redis"
    image: redis:7.0.4
    volumes:
      - ./data/redis:/data
    restart: always
  web:
    container_name: "journal-web"
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/code
    environment:
      - "SECRET_KEY="
      - "DEBUG=True"
      - "HOST_NAME=http://127.0.0.1"
      - "STATIC_ROOT=staticfiles"
      - "ROLLBAR_ACCESS_TOKEN="
    depends_on:
      - redis
    restart: always
# Daphne part based on ch.17 of A.Mele's "Django 4 by Example" book
# NB: secret key must be the same with `web`
  daphne:
    container_name: "journal-ws"
    build: .
    command: ["daphne", "-u", "/code/data/daphne/daphe.sock", "django_project.asgi:application"]
    volumes:
      - .:/code
    environment:
      - "SECRET_KEY="
      - "DEBUG=False"
      - "HOST_NAME=http://127.0.0.1"
      - "STATIC_ROOT=staticfiles"
      - "ROLLBAR_ACCESS_TOKEN="
    restart: always
  worker:
    container_name: "journal-worker"
    build: .
    volumes:
      - .:/code
    command: ['celery', '--workdir=/code', '-A', 'django_project', 'worker']
    environment:
      - "SECRET_KEY="
      - "DEBUG=False"
      - "HOST_NAME=http://127.0.0.1"
      - "ROLLBAR_ACCESS_TOKEN="
      - "TELEGRAM_BOT_TOKEN="
      - "TELEGRAM_ADMIN_ID=133637887"
    restart: always
  # Nginx config inspired by: https://saasitive.com/tutorial/django-celery-redis-postgres-docker-compose/
  nginx:
    container_name: "journal-nginx"
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media
    depends_on:
      - web
    restart: always