BACKUP_PATH = /Users/hazadus/webbackup
BACKUP_DATE = $(shell date +%Y_%m_%d_%H-%M)
FULL_PATH = $(BACKUP_PATH)/journal-$(BACKUP_DATE)
REMOTE_USER = username
REMOTE_IP = 0.0.0.0
REMOTE_DIR = /home/projects/journal/

lint:
	python -m flake8 .
	python -m isort --check-only --profile black .
	python -m black . --check
format:
	python -m isort --profile black .
	python -m black .
backup:
	rsync -arv --exclude=.venv --exclude=.git --exclude=__pycache__ --exclude=staticfiles $(REMOTE_USER)@$(REMOTE_IP):$(REMOTE_DIR) $(FULL_PATH)
test:
	docker exec journal-web coverage run --source='.' -m manage test
	docker exec journal-web coverage html
coverage:
	docker exec journal-web interrogate -vv .
up:
	docker compose up -d
	make coverage
	make test
	docker compose logs --follow
down:
	docker compose down
static:
	sudo rm -rf ./collectstatic
	python -m manage collectstatic
report:
	sudo docker exec journal-web python -m manage create_report
count:
	scc --exclude-dir .env,.git,.idea,.venv,staticfiles,__pycache__,./static/bootstrap-5.3.0-alpha1-dist,./static/fontawesome
