BACKUP_PATH = /Users/hazadus/webbackup
BACKUP_DATE = $(shell date +%Y_%m_%d_%H-%M)
FULL_PATH = $(BACKUP_PATH)/journal-$(BACKUP_DATE)
REMOTE_USER = username
REMOTE_IP = 0.0.0.0
REMOTE_DIR = /home/projects/journal/

backup:
	rsync -arv --exclude=.venv --exclude=.git --exclude=__pycache__ --exclude=staticfiles $(REMOTE_USER)@$(REMOTE_IP):$(REMOTE_DIR) $(FULL_PATH)
up:
	docker compose up -d
	docker exec journal-web coverage run --source='.' -m manage test
	docker exec journal-web coverage html
	docker compose logs --follow
test:
	docker exec journal-web coverage run --source='.' -m manage test
	docker exec journal-web coverage html
coverage:
	interrogate -vv .
down:
	docker compose down
static:
	sudo rm -rf ./collectstatic
	python -m manage collectstatic
report:
	sudo docker exec journal-web python -m manage create_report