from rest_framework import serializers

from .models import Task, TaskCategory


class TaskCategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = TaskCategory
        fields = ["id", "title"]


class TaskSerializer(serializers.ModelSerializer):
    # These fields will be generated by `annotate()` in TaskListApi.get_queryset():
    category_title = serializers.CharField()
    comments_count = serializers.IntegerField()
    new_comments_count = serializers.IntegerField()
    is_favorite = serializers.BooleanField()
    is_acquainted = serializers.BooleanField()

    class Meta:
        model = Task
        fields = [
            "id",
            "author",
            "category",
            "category_title",
            "title",
            "is_private",
            "is_archived",
            "attachment",
            "due_date",
            "created",
            "updated",
            "is_completed",
            "completed",
            "comments_count",
            "new_comments_count",
            "is_favorite",
            "is_acquainted",
        ]
